languageCode = 'en-us'
title = 'Mach engine - game engine & graphics toolkit for the future'
theme = "minimal"
canonifyURLs = true # Required for Hugo to rewrite Markdown links with baseURL in support of our site versioning

# Important: This should be configured according to the branch.
baseURL = 'https://machengine.org/next'
[params]
  branch = 'next'

  # Other branch-agnostic site params below
  alert = '**Mach v0.2 has been released!** For all the details check out [the announcement](https://devlog.hexops.com/2022/perfecting-webgpu-native/)'

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.docs]]
  name = 'Engine'
  identifier = 'Engine'
  weight = 100
[[menu.docs]]
  name = 'Core'
  identifier = 'Core'
  weight = 200
[[menu.docs]]
  name = 'Libraries'
  identifier = 'libs'
  weight = 300
[[menu.docs]]
  name = 'About'
  identifier = 'about'
  weight = 400

[[menu.docs]]
  parent = 'Engine'
  identifier = 'engine-overview'
  name = 'Overview'
  url = '/docs/engine'

[[menu.docs]]
  parent = 'Core'
  identifier = 'core-overview'
  name = 'Overview'
  url = '/docs/core'
  weight = 100
[[menu.docs]]
  parent = 'Core'
  identifier = 'core-overview'
  name = 'Overview'
  url = '/docs/core'
  weight = 200
[[menu.docs]]
  parent = 'Core'
  identifier = 'core-examples'
  name = 'Examples'
  url = '/docs/core/examples'
  weight = 300
[[menu.docs]]
  parent = 'Core'
  identifier = 'core-getting-started'
  name = 'Getting started'
  url = '/docs/core/getting-started'
  weight = 400
[[menu.docs]]
  parent = 'Core'
  identifier = 'core-known-issues'
  name = 'Known issues'
  url = '/docs/core/known-issues'
  weight = 500
[[menu.docs]]
  parent = 'Core'
  identifier = 'core-migrations'
  name = 'Migrations'
  url = '/docs/core/migrations'
  weight = 600

[[menu.docs]]
  parent = 'libs'
  identifier = 'libs-overview'
  name = 'Overview'
  url = '/docs/libs'
  weight = 100
[[menu.docs]]
  parent = 'libs'
  identifier = 'libs-glfw'
  name = 'mach/glfw'
  url = '/docs/libs/glfw'
  weight = 200
[[menu.docs]]
  parent = 'libs'
  identifier = 'libs-gpu'
  name = 'mach/gpu'
  url = '/docs/libs/gpu'
  weight = 300
[[menu.docs]]
  parent = 'libs'
  identifier = 'libs-freetype'
  name = 'mach/freetype'
  url = '/docs/libs/freetype'
  weight = 400
[[menu.docs]]
  parent = 'libs'
  identifier = 'libs-experimental'
  name = 'Experimental'
  url = '/docs/libs/experimental'
  weight = 500

[[menu.docs]]
  parent = 'about'
  identifier = 'about-goals'
  name = 'Project goals'
  url = '/docs/about/goals'
  weight = 100
