languageCode = 'en-us'
title = 'Mach: zig game engine & graphics toolkit'
description = "The Zig game engine & graphics toolkit for building high-performance, native, truly-cross-platform games, visualizations & desktop/mobile apps."
theme = "minimal"
canonifyURLs = true # Required for Hugo to rewrite Markdown links with baseURL in support of our site versioning

# Important: This should be configured according to the branch.
baseURL = 'https://machengine.org/next'
[params]
  branch = 'next'

  # Other branch-agnostic site params below
  alert = '**Mach v0.2 has been released!** For all the details check out [the announcement](https://devlog.hexops.com/2022/perfecting-webgpu-native/)'

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.engine]]
  identifier = 'engine'
  name = 'Engine overview'
  url = '/engine'
  weight = 100
[[menu.engine]]
  identifier = 'engine-math'
  name = 'Math'
  weight = 200
[[menu.engine]]
  parent = 'engine-math'
  identifier = 'engine-math-Overview'
  name = 'Overview'
  url = '/engine/math'
  weight = 201
[[menu.engine]]
  parent = 'engine-math'
  identifier = 'engine-math-coordinate-system'
  name = 'Coordinate system'
  url = '/engine/math/coordinate-system'
  weight = 202
[[menu.engine]]
  parent = 'engine-math'
  identifier = 'engine-math-matrix-storage'
  name = 'Matrix storage'
  url = '/engine/math/matrix-storage'
  weight = 203
[[menu.engine]]
  identifier = 'engine-known-issues'
  name = 'Known issues ⮕'
  url = '/about/known-issues'
  weight = 200


[[menu.core]]
  identifier = 'core'
  name = 'Core overview'
  url = '/core'
  weight = 100
[[menu.core]]
  identifier = 'core-examples'
  name = 'Examples'
  url = '/core/examples'
  weight = 200
[[menu.core]]
  identifier = 'core-getting-started'
  name = 'Getting started'
  url = '/core/getting-started'
  weight = 300
[[menu.core]]
  identifier = 'core-migrations'
  name = 'Migrations'
  url = '/core/migrations'
  weight = 400
[[menu.core]]
  identifier = 'core-known-issues'
  name = 'Known issues ⮕'
  url = '/about/known-issues'
  weight = 500



[[menu.libs]]
  identifier = 'libs'
  name = 'Libraries overview'
  url = '/libs'
  weight = 100
[[menu.libs]]
  identifier = 'libs-glfw'
  name = 'mach-glfw'
  url = '/libs/glfw'
  weight = 200
[[menu.libs]]
  identifier = 'libs-gpu'
  name = 'mach-gpu'
  url = '/libs/gpu'
  weight = 300
[[menu.libs]]
  identifier = 'libs-freetype'
  name = 'mach-freetype'
  url = '/libs/freetype'
  weight = 400
[[menu.libs]]
  identifier = 'libs-experimental'
  name = 'Experimental'
  url = '/libs/experimental'
  weight = 500
[[menu.libs]]
  identifier = 'libs-known-issues'
  name = 'Known issues ⮕'
  url = '/about/known-issues'
  weight = 600


[[menu.about]]
  identifier = 'about'
  name = 'About the project'
  url = '/about'
  weight = 100
[[menu.about]]
  identifier = 'about-goals'
  name = 'Project goals'
  url = '/about/goals'
  weight = 200
[[menu.about]]
  identifier = 'about-platforms'
  name = 'Platform support'
  url = '/about/platforms'
  weight = 300
[[menu.about]]
  identifier = 'about-known-issues'
  name = 'Known issues'
  url = '/about/known-issues'
  weight = 400
[[menu.about]]
  identifier = 'about-keycomp'
  name = 'Key components'
  url = '/engine'
  weight = 500

[[menu.about]]
  identifier = 'about-keycomp-engine'
  parent = 'about-keycomp'
  name = 'Engine'
  url = '/engine'
  weight = 500
[[menu.about]]
  identifier = 'about-keycomp-core'
  parent = 'about-keycomp'
  name = 'Core'
  url = '/core'
  weight = 600
[[menu.about]]
  identifier = 'about-keycomp-pkg'
  parent = 'about-keycomp'
  name = 'Packages'
  url = '/libs'
  weight = 700
