baseURL = 'https://machengine.org'
languageCode = 'en-us'
title = 'Mach engine - game engine & graphics toolkit for the future'
theme = "minimal"

[markup.goldmark.renderer]
unsafe = true

[mediaTypes]
  [mediaTypes.'video/mp4']
    suffixes = ['mp4']
  [mediaTypes.'video/ogg']
    suffixes = ['ogv']
  [mediaTypes.'video/webm']
    suffixes = ['webm']
