baseURL = 'https://machengine.org/next'
languageCode = 'en-us'
title = 'Mach engine - game engine & graphics toolkit for the future'
theme = "minimal"
canonifyURLs = true

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.docs]]
  name = 'Choose your journey'
  url = '/docs'
  weight = 100
[[menu.docs]]
  name = 'Engine'
  identifier = 'Engine'
  weight = 200
[[menu.docs]]
  name = 'Core'
  identifier = 'Core'
  weight = 300

[[menu.docs]]
  parent = 'Engine'
  identifier = 'engine-overview'
  name = 'Overview'
  url = '/docs/engine'

[[menu.docs]]
  parent = 'Core'
  identifier = 'core-overview'
  name = 'Overview'
  url = '/docs/core'
  weight = 100
[[menu.docs]]
  parent = 'Core'
  identifier = 'core-overview'
  name = 'Overview'
  url = '/docs/core'
  weight = 200
[[menu.docs]]
  parent = 'Core'
  identifier = 'core-examples'
  name = 'Examples'
  url = '/docs/core/examples'
  weight = 300
[[menu.docs]]
  parent = 'Core'
  identifier = 'core-getting-started'
  name = 'Getting started'
  url = '/docs/core/getting-started'
  weight = 400
[[menu.docs]]
  parent = 'Core'
  identifier = 'core-libraries'
  name = 'Libraries'
  url = '/docs/core/libraries'
  weight = 500
[[menu.docs]]
  parent = 'Core'
  identifier = 'core-known-issues'
  name = 'Known issues'
  url = '/docs/core/known-issues'
  weight = 600
[[menu.docs]]
  parent = 'Core'
  identifier = 'core-nixos-usage'
  name = 'NixOS usage'
  url = '/docs/core/nixos-usage'
  weight = 700
