baseURL = 'https://machengine.org/next'
languageCode = 'en-us'
title = 'Mach engine - game engine & graphics toolkit for the future'
theme = "minimal"
canonifyURLs = true

[markup.goldmark.renderer]
unsafe = true
